package com.example.quizapp.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity for one gallery item.
 *
 * This is based on the existing BildeOppforing model, but Room stores
 * the image reference as a String instead of Uri.
 */
@Entity(tableName = "gallery_items")
data class GalleryItemEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val name: String,
    val uri: String
)

/*
 * TODO (required): Add mapping helpers between GalleryItemEntity and BildeOppforing.
 * TODO (required): Store the image URI as String, not Bitmap or drawable data.
 * TODO (required): Convert the stored uri String to Uri when reading from Room.
 * TODO (required): Convert Uri to String when saving items to Room.
 * TODO (required): Preserve compatibility with both built-in images and user-added images.
 * TODO (required): Decide how built-in images from Oblig 1 should be represented in Room.
 * TODO (required): Decide whether id should be generated by Room or kept compatible with the existing model.
 * TODO (optional): Add a small helper comment or mapper file later if the team wants cleaner conversions.
 */
